apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: kubernetes-kops-operator-controller-manager
  name: kubernetes-kops-operator-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-kops-operator-controller-manager
  namespace: kubernetes-kops-operator-system
  labels:
    control-plane: kubernetes-kops-operator-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: kubernetes-kops-operator-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: kubernetes-kops-operator-controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: controller:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      serviceAccountName: kubernetes-kops-operator-controller-manager
      terminationGracePeriodSeconds: 10
