# permissions for end users to view kopsmachinepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kopsmachinepool-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - kopsmachinepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - kopsmachinepools/status
  verbs:
  - get
